"""empty message

Revision ID: 3713d232ec0f
Revises: 50d173ce5902
Create Date: 2023-10-06 21:00:07.064491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3713d232ec0f'
down_revision = '50d173ce5902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index('ix_artist_description')
        batch_op.create_index(batch_op.f('ix_artist_description'), ['description'], unique=False)
        batch_op.drop_index('ix_artist_genre')
        batch_op.create_index(batch_op.f('ix_artist_genre'), ['genre'], unique=False)
        batch_op.drop_index('ix_artist_hometown')
        batch_op.create_index(batch_op.f('ix_artist_hometown'), ['hometown'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('ix_event_event_date')
        batch_op.create_index(batch_op.f('ix_event_event_date'), ['event_date'], unique=False)
        batch_op.drop_index('ix_event_event_description')
        batch_op.create_index(batch_op.f('ix_event_event_description'), ['event_description'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_user_password')
        batch_op.create_index(batch_op.f('ix_user_user_password'), ['user_password'], unique=False)

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_index('ix_venue_max_capacity')
        batch_op.create_index(batch_op.f('ix_venue_max_capacity'), ['max_capacity'], unique=False)
        batch_op.drop_index('ix_venue_venue_address')
        batch_op.create_index(batch_op.f('ix_venue_venue_address'), ['venue_address'], unique=False)
        batch_op.drop_index('ix_venue_venue_description')
        batch_op.create_index(batch_op.f('ix_venue_venue_description'), ['venue_description'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_venue_description'))
        batch_op.create_index('ix_venue_venue_description', ['venue_description'], unique=False)
        batch_op.drop_index(batch_op.f('ix_venue_venue_address'))
        batch_op.create_index('ix_venue_venue_address', ['venue_address'], unique=False)
        batch_op.drop_index(batch_op.f('ix_venue_max_capacity'))
        batch_op.create_index('ix_venue_max_capacity', ['max_capacity'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_user_password'))
        batch_op.create_index('ix_user_user_password', ['user_password'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_event_description'))
        batch_op.create_index('ix_event_event_description', ['event_description'], unique=False)
        batch_op.drop_index(batch_op.f('ix_event_event_date'))
        batch_op.create_index('ix_event_event_date', ['event_date'], unique=False)

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_hometown'))
        batch_op.create_index('ix_artist_hometown', ['hometown'], unique=False)
        batch_op.drop_index(batch_op.f('ix_artist_genre'))
        batch_op.create_index('ix_artist_genre', ['genre'], unique=False)
        batch_op.drop_index(batch_op.f('ix_artist_description'))
        batch_op.create_index('ix_artist_description', ['description'], unique=False)

    # ### end Alembic commands ###
