"""empty message

Revision ID: e8e05c18b275
Revises: f9f345cedceb
Create Date: 2023-10-08 20:27:17.764586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e05c18b275'
down_revision = 'f9f345cedceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.drop_index('ix_user_user_password')
        batch_op.drop_column('user_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_password', sa.VARCHAR(length=32), nullable=True))
        batch_op.create_index('ix_user_user_password', ['user_password'], unique=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
